version: '3'

tasks:
  dev:
    silent: true
    ignore_error: true
    cmds:
      - defer: devspace reset pods
      - devspace dev
  deploy:
    silent: true
    env:
      KOCACHE: true
    cmds:
      - ko apply -f kubectl.yaml
  build:
    env:
      GOOS: linux
      GOARCH: amd64
      CGO_ENABLED: 0
    cmds:
      - go build -ldflags="-s -w" -o ./bin/server ./...
      - zip -r ./bin/server.zip ./bin/server
  release:
    deps:
      - build
      - deploy
